name: ARM Template Validation Pipeline

on:
  push:
    paths:
      - 'templates/**'
  workflow_dispatch:

jobs:
  validate-arm-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    
    - name: Run ARM-TTK Tests and Capture All Results
      shell: pwsh
      run: |
        Import-Module ./tools/arm-ttk/arm-ttk/arm-ttk.psd1
        "## ARM-TTK Test Results for azuredeploy.json" | Out-File -FilePath results.txt -Encoding utf8
    
        # Run the test and capture all output (stdout + stderr)
        $output = Test-AzTemplate -TemplatePath ./templates/azuredeploy.json -ErrorAction Continue 2>&1
        $output | Out-String | Out-File -FilePath results.txt -Append -Encoding utf8




    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script and Append Output
      run: |
        echo "## Python Script Output" >> results.txt
        python compare.py >> results.txt
    - name: Display Results
      run: cat results.txt

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: results.txt
