name: ARM Template Validation Pipeline

on:
  push:
    paths:
      - 'templates/**'
  workflow_dispatch:

jobs:
  validate-arm-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Run ARM-TTK Tests and Capture All Results
      shell: pwsh
      run: |
        Start-Transcript -Path results.txt -Append
        Import-Module ./tools/arm-ttk/arm-ttk/arm-ttk.psd1
        Test-AzTemplate -TemplatePath ./templates/azuredeploy.json -ErrorAction Continue
        Stop-Transcript

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script and Append Output
      run: |
        echo "## Python Script Output" >> results.txt
        python compare.py >> results.txt

    - name: Generate Excel Report
      run: |
        pip install openpyxl
        python generate_excel.py

    - name: Upload Excel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: validation_results.xlsx
