name: ARM Template Validation Pipeline

on:
  push:
    paths:
      - 'templates/**'
  workflow_dispatch:

jobs:
  validate-arm-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v3

    - name: Clone ARM-TTK from GitHub
      run: git clone https://github.com/Azure/arm-ttk.git tools/arm-ttk

    - name: Import and Run ARM-TTK Tests
      run: |
        pwsh -Command "Import-Module ./tools/arm-ttk/arm-ttk.psd1"
        pwsh -Command "Test-AzTemplate -TemplatePath ./templates"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script
      run: python compare.py

    - name: Document Findings
      run: |
        echo "## Validation Results" > results.md
        echo "ARM-TTK and parameter analysis completed." >> results.md

    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: results.md
