name: ARM Template Validation Pipeline

on:
  push:
    paths:
      - 'templates/**'
  workflow_dispatch:

jobs:
  validate-arm-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v4

    - name: Run ARM-TTK Tests and Capture All Results
      shell: pwsh
      run: |
        try {
          Import-Module ./tools/arm-ttk/arm-ttk/arm-ttk.psd1
          "## ARM-TTK Test Results" | Out-File -FilePath results.txt -Encoding utf8
          $files = Get-ChildItem -Path ./templates -Filter *.json
          foreach ($file in $files) {
            "### Testing $($file.Name)" | Out-File -FilePath results.txt -Append -Encoding utf8
            $results = Test-AzTemplate -TemplatePath $file.FullName -ErrorAction Continue 2>&1
            $results | Out-String | Out-File -FilePath results.txt -Append -Encoding utf8
          }
        } catch {
          "An error occurred while running ARM-TTK tests: $_" | Out-File -FilePath results.txt -Append -Encoding utf8
        } finally {
          # Always exit with 0 to prevent pipeline failure
          exit 0
        }


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Python Script and Append Output
      run: |
        echo "## Python Script Output" >> results.txt
        python compare.py >> results.txt
    - name: Display Results
      run: cat results.txt

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: validation-results
        path: results.txt
